version: '3'

services:

  server:
    image: jetbrains/teamcity-server:2019.1-linux
    networks:
      - web
      - default
    volumes:
      - "/opt/teamcity/data:/data/teamcity_server/datadir"
      - "/opt/teamcity/logs:/opt/teamcity/logs"
    hostname: ${VIRTUAL_HOST}
    ports:
      - "8111"
    environment:
      HUB_URL: http://chrome:4444/wd/hub # for Selenium/Chrome
    depends_on:
      - postgres
      - chrome # Selenium/Chrome container
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=server"
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST}"
      - "traefik.docker.network=web"
      - "traefik.port=8111"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  agent:
    build: https://github.com/UsAndRufus/docker-teamcity-agent-rbenv.git
    env_file: .env
    volumes:
      - 'teamcity_agent_rbenv_conf:/data/teamcity_agent/conf'
      - '/opt/teamcity/platform/system:/data/teamcity_agent/platform/system'
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    depends_on:
      - postgres
      - redis
    #     if you need docker inside the agent
    #     (http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/)
    labels:
      - "traefik.enable=false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  postgres:
    build: ./postgres
    volumes:
      - "/opt/teamcity/pg_data:/var/lib/postgresql/data"
      - "/opt/teamcity/pg_backup:/backups"
    env_file: .env
    labels:
      - "traefik.enable=false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - 5342:5342
    restart: always

  redis:
    image: redis:3.2
    labels:
      - "traefik.enable=false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  traefik:
    image: traefik:1.7
    restart: on-failure
    command:
      - --logLevel=ERROR
      - --docker
      - --docker.watch=true
      - --docker.exposedByDefault=false
      - --docker.domain=${VIRTUAL_HOST}
      - --defaultEntryPoints=http,https
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --acme=true
      - --acme.domains=${LETSENCRYPT_HOST}
      - --acme.email=${LETSENCRYPT_EMAIL}
      - --acme.storage=acme.json
      - --acme.OnHostRule=false
      - --acme.onDemand=false
      - --acme.entryPoint=https
      - --acme.httpChallenge
      - --acme.httpChallenge.entryPoint=http
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/acme.json:/acme.json
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  chrome:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm

volumes:
        teamcity_agent_rbenv_conf:

networks:
  web:
    external: true
